name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r devsecops-lab/requirements.txt

      - name: Criar banco
        run: |
          python devsecops-lab/criar_db.py

      - name: Iniciar aplicação
        run: |
          gunicorn --chdir devsecops-lab/ app:app \
            --bind 0.0.0.0:5000 \
            > gunicorn.log 2>&1 &

      - name: Aguardar aplicação
        run: |
          for i in {1..30}; do
            if curl --fail --silent http://127.0.0.1:5000/ > /dev/null; then
              echo "Aplicação está disponível!"
              exit 0
            fi

            echo "Aguardando aplicação... tentativa $i/30"
            sleep 2
          done

          echo "A aplicação não iniciou corretamente."
          echo "===== Gunicorn log ====="
          cat gunicorn.log
          exit 1

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: http://127.0.0.1:5000

